// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantAPI.Data;

#nullable disable

namespace RestaurantAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427054418_SeedUpgrade")]
    partial class SeedUpgrade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantAPI.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BookingNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("GuestCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("TableId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("RestaurantAPI.Models.DiningTable", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TableNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("TableId");

                    b.ToTable("DiningTables");

                    b.HasData(
                        new
                        {
                            TableId = 1,
                            Capacity = 2,
                            Status = 0,
                            TableNumber = "Royal-01"
                        },
                        new
                        {
                            TableId = 2,
                            Capacity = 2,
                            Status = 0,
                            TableNumber = "Royal-02"
                        },
                        new
                        {
                            TableId = 3,
                            Capacity = 4,
                            Status = 0,
                            TableNumber = "Garden-01"
                        },
                        new
                        {
                            TableId = 4,
                            Capacity = 4,
                            Status = 0,
                            TableNumber = "Garden-02"
                        },
                        new
                        {
                            TableId = 5,
                            Capacity = 6,
                            Status = 0,
                            TableNumber = "Family-01"
                        },
                        new
                        {
                            TableId = 6,
                            Capacity = 6,
                            Status = 0,
                            TableNumber = "Family-02"
                        },
                        new
                        {
                            TableId = 7,
                            Capacity = 8,
                            Status = 0,
                            TableNumber = "VIP-01"
                        },
                        new
                        {
                            TableId = 8,
                            Capacity = 8,
                            Status = 0,
                            TableNumber = "VIP-02"
                        },
                        new
                        {
                            TableId = 9,
                            Capacity = 4,
                            Status = 0,
                            TableNumber = "Terrace-01"
                        },
                        new
                        {
                            TableId = 10,
                            Capacity = 2,
                            Status = 0,
                            TableNumber = "Terrace-02"
                        });
                });

            modelBuilder.Entity("RestaurantAPI.Models.MenuCategory", b =>
                {
                    b.Property<int>("MenuCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuCategoryId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MenuCategoryId");

                    b.ToTable("MenuCategories");

                    b.HasData(
                        new
                        {
                            MenuCategoryId = 1,
                            Code = "ST",
                            Name = "Starters"
                        },
                        new
                        {
                            MenuCategoryId = 2,
                            Code = "MC",
                            Name = "Main Course"
                        },
                        new
                        {
                            MenuCategoryId = 3,
                            Code = "DR",
                            Name = "Drinks"
                        },
                        new
                        {
                            MenuCategoryId = 4,
                            Code = "DS",
                            Name = "Desserts"
                        },
                        new
                        {
                            MenuCategoryId = 5,
                            Code = "FF",
                            Name = "Fast Food"
                        },
                        new
                        {
                            MenuCategoryId = 6,
                            Code = "SI",
                            Name = "South Indian"
                        });
                });

            modelBuilder.Entity("RestaurantAPI.Models.MenuItem", b =>
                {
                    b.Property<int>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuItemId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("MenuCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MenuItemId");

                    b.HasIndex("MenuCategoryId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            MenuItemId = 1,
                            Description = "Hot soup",
                            IsAvailable = true,
                            MenuCategoryId = 1,
                            Name = "Tomato Soup",
                            Price = 120m
                        },
                        new
                        {
                            MenuItemId = 2,
                            Description = "Grilled paneer",
                            IsAvailable = true,
                            MenuCategoryId = 1,
                            Name = "Paneer Tikka",
                            Price = 180m
                        },
                        new
                        {
                            MenuItemId = 3,
                            Description = "Spicy wings",
                            IsAvailable = true,
                            MenuCategoryId = 1,
                            Name = "Chicken Wings",
                            Price = 220m
                        },
                        new
                        {
                            MenuItemId = 4,
                            Description = "Spicy curry",
                            IsAvailable = true,
                            MenuCategoryId = 2,
                            Name = "Chicken Curry",
                            Price = 250m
                        },
                        new
                        {
                            MenuItemId = 5,
                            Description = "Special biryani",
                            IsAvailable = true,
                            MenuCategoryId = 2,
                            Name = "Mutton Biryani",
                            Price = 320m
                        },
                        new
                        {
                            MenuItemId = 6,
                            Description = "Veg rice",
                            IsAvailable = true,
                            MenuCategoryId = 2,
                            Name = "Veg Fried Rice",
                            Price = 180m
                        },
                        new
                        {
                            MenuItemId = 7,
                            Description = "Soft naan",
                            IsAvailable = true,
                            MenuCategoryId = 2,
                            Name = "Butter Naan",
                            Price = 40m
                        },
                        new
                        {
                            MenuItemId = 8,
                            Description = "Fresh juice",
                            IsAvailable = true,
                            MenuCategoryId = 3,
                            Name = "Mango Juice",
                            Price = 90m
                        },
                        new
                        {
                            MenuItemId = 9,
                            Description = "Chilled coffee",
                            IsAvailable = true,
                            MenuCategoryId = 3,
                            Name = "Cold Coffee",
                            Price = 120m
                        },
                        new
                        {
                            MenuItemId = 10,
                            Description = "Refreshing drink",
                            IsAvailable = true,
                            MenuCategoryId = 3,
                            Name = "Lemon Soda",
                            Price = 70m
                        },
                        new
                        {
                            MenuItemId = 11,
                            Description = "Vanilla scoop",
                            IsAvailable = true,
                            MenuCategoryId = 4,
                            Name = "Ice Cream",
                            Price = 100m
                        },
                        new
                        {
                            MenuItemId = 12,
                            Description = "Sweet dessert",
                            IsAvailable = true,
                            MenuCategoryId = 4,
                            Name = "Gulab Jamun",
                            Price = 80m
                        },
                        new
                        {
                            MenuItemId = 13,
                            Description = "Crispy burger",
                            IsAvailable = true,
                            MenuCategoryId = 5,
                            Name = "Veg Burger",
                            Price = 150m
                        },
                        new
                        {
                            MenuItemId = 14,
                            Description = "Chicken burger",
                            IsAvailable = true,
                            MenuCategoryId = 5,
                            Name = "Chicken Burger",
                            Price = 180m
                        },
                        new
                        {
                            MenuItemId = 15,
                            Description = "Crispy fries",
                            IsAvailable = true,
                            MenuCategoryId = 5,
                            Name = "French Fries",
                            Price = 120m
                        },
                        new
                        {
                            MenuItemId = 16,
                            Description = "Crispy dosa",
                            IsAvailable = true,
                            MenuCategoryId = 6,
                            Name = "Masala Dosa",
                            Price = 90m
                        },
                        new
                        {
                            MenuItemId = 17,
                            Description = "Soft idli",
                            IsAvailable = true,
                            MenuCategoryId = 6,
                            Name = "Idli",
                            Price = 50m
                        },
                        new
                        {
                            MenuItemId = 18,
                            Description = "Crispy vada",
                            IsAvailable = true,
                            MenuCategoryId = 6,
                            Name = "Vada",
                            Price = 60m
                        },
                        new
                        {
                            MenuItemId = 19,
                            Description = "South breakfast",
                            IsAvailable = true,
                            MenuCategoryId = 6,
                            Name = "Pongal",
                            Price = 70m
                        },
                        new
                        {
                            MenuItemId = 20,
                            Description = "Traditional meal",
                            IsAvailable = true,
                            MenuCategoryId = 6,
                            Name = "Sambar Rice",
                            Price = 110m
                        });
                });

            modelBuilder.Entity("RestaurantAPI.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("BookingId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RestaurantAPI.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("KitchenStatus")
                        .HasColumnType("int");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Booking", b =>
                {
                    b.HasOne("RestaurantAPI.Models.DiningTable", "Table")
                        .WithMany("Bookings")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("RestaurantAPI.Models.MenuItem", b =>
                {
                    b.HasOne("RestaurantAPI.Models.MenuCategory", "MenuCategory")
                        .WithMany("MenuItems")
                        .HasForeignKey("MenuCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuCategory");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Order", b =>
                {
                    b.HasOne("RestaurantAPI.Models.Booking", "Booking")
                        .WithMany("Orders")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("RestaurantAPI.Models.OrderItem", b =>
                {
                    b.HasOne("RestaurantAPI.Models.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantAPI.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Booking", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("RestaurantAPI.Models.DiningTable", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("RestaurantAPI.Models.MenuCategory", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("RestaurantAPI.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
